apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth
data:
  mysqluser: {{ .Values.mysqluser }}
  mysqlpass: {{ .Values.mysqlpass }}
  mysqlip: {{ .Values.mysqlip }}
  mysqldb: {{ .Values.mysqldb }}
  mongodbuser: {{ .Values.mongodbuser }}
  mongodbpass: {{ .Values.mongodbpass }}
  mongodbip: {{ .Values.mongodbip }}
  mongodb: {{ .Values.mongodb }}