apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: apache
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}